//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// InboxPage defines model for InboxPage.
type InboxPage struct {
	// HasMore Whether another page is available after this one.
	HasMore  bool             `json:"hasMore"`
	Limit    int              `json:"limit"`
	Messages []MessageSummary `json:"messages"`
	Offset   int              `json:"offset"`
}

// Message defines model for Message.
type Message struct {
	// Body Original raw MIME body, without RFC 822 headers or the separating blank line.
	Body      string    `json:"body"`
	ExpiresAt time.Time `json:"expiresAt"`
	From      string    `json:"from"`

	// Headers Original RFC 822 header block, without the separating blank line.
	Headers   string              `json:"headers"`
	Id        string              `json:"id"`
	Received  time.Time           `json:"received"`
	Recipient openapi_types.Email `json:"recipient"`

	// Size Raw message size in bytes.
	Size    int64  `json:"size"`
	Subject string `json:"subject"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	ExpiresAt time.Time           `json:"expiresAt"`
	From      string              `json:"from"`
	Id        string              `json:"id"`
	Received  time.Time           `json:"received"`
	Recipient openapi_types.Email `json:"recipient"`

	// Size Raw message size in bytes.
	Size    int64  `json:"size"`
	Subject string `json:"subject"`
}

// Inbox defines model for Inbox.
type Inbox = openapi_types.Email

// ListInboxMessagesParams defines parameters for ListInboxMessages.
type ListInboxMessagesParams struct {
	// Limit Maximum messages to return (default 25, maximum 100).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Zero-based number of messages to skip (default 0).
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListInboxMessages List active messages for an inbox
	// (GET /api/v1/inboxes/{inbox})
	ListInboxMessages(w http.ResponseWriter, r *http.Request, inbox Inbox, params ListInboxMessagesParams)
	// GetMessage Retrieve one active message, with RFC 822 headers and MIME body separated
	// (GET /api/v1/messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id string)
	// Healthcheck Check whether the HTTP service is responsive
	// (GET /healthz)
	Healthcheck(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListInboxMessages operation middleware
func (siw *ServerInterfaceWrapper) ListInboxMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "inbox" -------------
	var inbox Inbox

	err = runtime.BindStyledParameterWithOptions("simple", "inbox", r.PathValue("inbox"), &inbox, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "email", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inbox", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInboxMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInboxMessages(w, r, inbox, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthcheck operation middleware
func (siw *ServerInterfaceWrapper) Healthcheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthcheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.Healthcheck)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/inboxes/{inbox}", wrapper.ListInboxMessages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/messages/{id}", wrapper.GetMessage)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFdvb9u2E/4qB/764jdAtmXHTlO9atC1a4AGDZIMw9pkAC2eLDYUqR4pJ27g7z6Qki0rsrN26F5Fisi7",
	"55577o8fWWqK0mjUzrLkkZWceIEOKbyd6bl58A8CbUqydNJolrB3lVJAmMpSonaABZcKuBCE1kbw++WH",
	"AerUCBRwn6MGjSlay2k1ZBGT3kDJXc4ipnmBLGEyeIkY4ddKEgqWOKowYjbNseDePT7wolT+7LySSgym",
	"J5PXrii932G2kiximaGCO5awAIZFzK1Kf946knrB1uu1t29Loy2G0K6cIb7At0SG+hFe5wiFB71AsM4Q",
	"QmoqJUAbB3MEQi6GbL3eYGzJuuAL9C8lmRLJydpZzu25Iez7+SNHlyMB1yb8Lb1DaYEvuVR8rhB45pDA",
	"5dKC0egZ3JJRs9QEOjdGIddsHTElC+k6tE1mESuklkVVsGS8vSO1wwWSv9MEG9BKh0V4eEGYsYT9b9Rq",
	"ZNQEPDqvL1xVRcFpxdZbo5yIh3eTZRa7OOIdGHEfxnpXA59bTFtbm9iiLaO3Wytm/gVT5x030LxnrtTH",
	"jCWffzCWp/mbG7HqJ+8jyYXUXAHxezg/O38L/lwE99LlpnJw+e4NnEwmkCMXSBaMzyOCRV9kTuoFzBXX",
	"d6Dkk8Sy8eRoOjvuqzhija1nwHS9wlyZ9K7F9J0A3pEpErCoBdLr5t9DQ4sbutFXVWA6gT9NRbBEkplM",
	"uYcBvuj31F43rZsQoprWfgZv2xxuUtKrKHwoJaE97eqLTeLJ8SA+GUxm15NxMp4lcfxptzsI7nDgZIH7",
	"uM3IFF1zfQL23ZOie+vlbHqEKfIjjI+mmM7m4uXJ+BUKgenL46l4xSLfAB2Sz9tfn/kgiwevbh+PJusX",
	"+8wTpiiXKA5HGv9opNve/XOaa8Ss/Lanu13y+7aLym8IUsN85dB2xHYyPdpxIbU7nrLn+0TEbK3BLvx/",
	"qUcp2C4jjQ5aHzsZiHZ01wTdl6+3L3Vm9vCBXAyMVis4vTiDzPcDLEpDnFbgh2ClBQTa4VSpDXMWap/A",
	"K2cK7mTKlVpFN1p7ypRa+bkAuY+9nhUBbemGcJ0jhWmiDZjK1fbrYX16cTa80Z4a6QJ3TcL9BxaxJZKt",
	"IY+H8TAO3bxEzUvJEnY0HA/jWsN5qMURL+VoOR6FOY529Bge1v7Toh4AvnJDRs4ES9gHaV0Yludtg9/d",
	"Ow506/bIKNwOfbpL8Dl/8KJpqXMGCF1FGv4vMOOVcjCZRVA058Zx/Mt2KflaIa3arWQzadotpLHQjNPa",
	"BEvGcfz8cO3D/IRkBnNuUYCuijkSmKyD2d7JskV8GON2LO4B+U+z9vbJQjSJY/8nNdo1jYGXpWoqafTF",
	"euSPO46eG6jtKhSqoRv9ab3lmAx46uRyu2jZCDTeo3WQSbJu6FU3i+NDvrbgR51Vbh26QzM1gtSeugmF",
	"xzXUa6c/vxHw5sToUYrD8v0N3WbD6Om2v0Wakn+tts7h7NdGkChgvgrjOOAA1KI0UrtDO7J4dkH+/nny",
	"n+Z9w8uerHsuuokICZ7G0+e3b2HQhrUbH3wuDUHONy1R/BSNXKIjiUsMfbQLsd6beosc16Ld9zbrFIpa",
	"Szly5fJvB+XzPnxPc0zvWC8Ve8i4QlrKNPTx2vRq+CSAN96W/6kVfkJ4Sb2/vr4A215svMhlkxr/ab9k",
	"L7FUPMU67pUfKpvJIEzBpfbyrEixhOXOlTYZjXZXhfXt+u8BAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
